bfl::UKFPrediction Class Reference
#include <UKFPrediction.h>
Public Types
enum class UKFPredictionType { Generic
, Additive
 }
Public Member Functions
UKFPrediction (std::unique_ptr< StateModel > state_model, const size_t n, const double alpha, const double beta, const double kappa) noexcept
UKFPrediction (std::unique_ptr< AdditiveStateModel > state_model, const size_t n, const double alpha, const double beta, const double kappa) noexcept
UKFPrediction (const UKFPrediction &prediction) noexcept=delete
UKFPrediction & operator= (const UKFPrediction &prediction) noexcept=delete
UKFPrediction (UKFPrediction &&prediction) noexcept
UKFPrediction & operator= (UKFPrediction &&prediction) noexcept
virtual ~UKFPrediction () noexcept=default
StateModel & getStateModel () noexcept override
void predict (const GaussianMixture &prev_state, GaussianMixture &pred_state) override
bool skip (const std::string &what_step, const bool status) override
bool is_skipping () override
Protected Member Functions
void predictStep (const GaussianMixture &prev_state, GaussianMixture &pred_state) override
Private Attributes
std::unique_ptr< StateModel > state_model_
std::unique_ptr< AdditiveStateModel > add_state_model_
UKFPredictionType type_
Distinguish between a UKFPrediction using a generic StateModel and a UKFPrediction using an AdditiveStateModel.
sigma_point::UTWeight ut_weight_
Unscented transform weight.
bool skip_ = false
Detailed Description
Definition at line 25 of file UKFPrediction.h.
Member Enumeration Documentation
UKFPredictionType
enum bfl::UKFPrediction::UKFPredictionType [strong]
Enumerator
Generic
Additive
Definition at line 28 of file UKFPrediction.h.
Constructor & Destructor Documentation
UKFPrediction() [1/4]
UKFPrediction::UKFPrediction (std::unique_ptr< StateModel > state_model, const size_t n, const double alpha, const double beta, const double kappa) [noexcept]
Definition at line 15 of file UKFPrediction.cpp.
UKFPrediction() [2/4]
UKFPrediction::UKFPrediction (std::unique_ptr< AdditiveStateModel > state_model, const size_t n, const double alpha, const double beta, const double kappa) [noexcept]
Definition at line 29 of file UKFPrediction.cpp.
UKFPrediction() [3/4]
bfl::UKFPrediction::UKFPrediction (const UKFPrediction & prediction) [delete], [noexcept]
UKFPrediction() [4/4]
UKFPrediction::UKFPrediction (UKFPrediction && prediction) [noexcept]
Definition at line 43 of file UKFPrediction.cpp.
 UKFPrediction()
virtual bfl::UKFPrediction::~UKFPrediction () [virtual], [default], [noexcept]
Member Function Documentation
getStateModel()
bfl::StateModel & UKFPrediction::getStateModel () [override], [virtual], [noexcept]
Implements bfl::GaussianPrediction.
Definition at line 71 of file UKFPrediction.cpp.
is_skipping()
bool GaussianPrediction::is_skipping () [override], [virtual], [inherited]
Implements bfl::Skippable.
Definition at line 56 of file GaussianPrediction.cpp.
operator=() [1/2]
UKFPrediction& bfl::UKFPrediction::operator= (const UKFPrediction & prediction) [delete], [noexcept]
operator=() [2/2]
UKFPrediction & UKFPrediction::operator= (UKFPrediction && prediction) [noexcept]
Definition at line 52 of file UKFPrediction.cpp.
References bfl::GaussianPrediction::operator=().
predict()
void GaussianPrediction::predict (const GaussianMixture & prev_state, GaussianMixture & pred_state) [override], [virtual], [inherited]
Implements bfl::GaussianMixturePrediction.
Definition at line 18 of file GaussianPrediction.cpp.
predictStep()
void UKFPrediction::predictStep (const GaussianMixture & prev_state, GaussianMixture & pred_state) [override], [protected], [virtual]
Implements bfl::GaussianPrediction.
Definition at line 80 of file UKFPrediction.cpp.
References bfl::GaussianMixture::augmentWithNoise(), and bfl::sigma_point::unscented_transform().
skip()
bool GaussianPrediction::skip (const std::string & what_step, const bool status) [override], [virtual], [inherited]
Implements bfl::Skipper.
Definition at line 27 of file GaussianPrediction.cpp.
Member Data Documentation
add_state_model_
std::unique_ptr<AdditiveStateModel> bfl::UKFPrediction::add_state_model_ [private]
Definition at line 58 of file UKFPrediction.h.
skip_
bool bfl::GaussianPrediction::skip_ = false [private], [inherited]
Definition at line 52 of file GaussianPrediction.h.
state_model_
std::unique_ptr<StateModel> bfl::UKFPrediction::state_model_ [private]
Definition at line 56 of file UKFPrediction.h.
type_
UKFPredictionType bfl::UKFPrediction::type_ [private]
Distinguish between a UKFPrediction using a generic StateModel and a UKFPrediction using an AdditiveStateModel.
Definition at line 64 of file UKFPrediction.h.
ut_weight_
sigma_point::UTWeight bfl::UKFPrediction::ut_weight_ [private]
Unscented transform weight.
Definition at line 69 of file UKFPrediction.h.
The documentation for this class was generated from the following files:
/home/xenvre/robot-code/bfl_robotology/src/BayesFilters/include/BayesFilters/UKFPrediction.h
/home/xenvre/robot-code/bfl_robotology/src/BayesFilters/src/UKFPrediction.cpp