bfl::KFPrediction Class Reference
#include <KFPrediction.h>
Public Member Functions
KFPrediction (std::unique_ptr< LinearStateModel > state_model) noexcept
KFPrediction (const KFPrediction &prediction) noexcept=delete
KFPrediction & operator= (const KFPrediction &prediction) noexcept=delete
KFPrediction (KFPrediction &&prediction) noexcept
KFPrediction & operator= (KFPrediction &&prediction) noexcept
virtual ~KFPrediction () noexcept=default
StateModel & getStateModel () noexcept override
void predict (const GaussianMixture &prev_state, GaussianMixture &pred_state) override
bool skip (const std::string &what_step, const bool status) override
bool is_skipping () override
Protected Member Functions
void predictStep (const GaussianMixture &prev_state, GaussianMixture &pred_state) override
Private Attributes
std::unique_ptr< LinearStateModel > state_model_
bool skip_ = false
Detailed Description
Definition at line 23 of file KFPrediction.h.
Constructor & Destructor Documentation
KFPrediction() [1/3]
KFPrediction::KFPrediction (std::unique_ptr< LinearStateModel > state_model) [noexcept]
Definition at line 14 of file KFPrediction.cpp.
KFPrediction() [2/3]
bfl::KFPrediction::KFPrediction (const KFPrediction & prediction) [delete], [noexcept]
KFPrediction() [3/3]
KFPrediction::KFPrediction (KFPrediction && prediction) [noexcept]
Definition at line 19 of file KFPrediction.cpp.
 KFPrediction()
virtual bfl::KFPrediction::~KFPrediction () [virtual], [default], [noexcept]
Member Function Documentation
getStateModel()
bfl::StateModel & KFPrediction::getStateModel () [override], [virtual], [noexcept]
Implements bfl::GaussianPrediction.
Definition at line 38 of file KFPrediction.cpp.
is_skipping()
bool GaussianPrediction::is_skipping () [override], [virtual], [inherited]
Implements bfl::Skippable.
Definition at line 56 of file GaussianPrediction.cpp.
operator=() [1/2]
KFPrediction& bfl::KFPrediction::operator= (const KFPrediction & prediction) [delete], [noexcept]
operator=() [2/2]
KFPrediction & KFPrediction::operator= (KFPrediction && prediction) [noexcept]
Definition at line 25 of file KFPrediction.cpp.
References bfl::GaussianPrediction::operator=().
predict()
void GaussianPrediction::predict (const GaussianMixture & prev_state, GaussianMixture & pred_state) [override], [virtual], [inherited]
Implements bfl::GaussianMixturePrediction.
Definition at line 18 of file GaussianPrediction.cpp.
predictStep()
void KFPrediction::predictStep (const GaussianMixture & prev_state, GaussianMixture & pred_state) [override], [protected], [virtual]
Implements bfl::GaussianPrediction.
Definition at line 44 of file KFPrediction.cpp.
References bfl::GaussianMixture::components, bfl::GaussianMixture::covariance(), and bfl::GaussianMixture::mean().
skip()
bool GaussianPrediction::skip (const std::string & what_step, const bool status) [override], [virtual], [inherited]
Implements bfl::Skipper.
Definition at line 27 of file GaussianPrediction.cpp.
Member Data Documentation
skip_
bool bfl::GaussianPrediction::skip_ = false [private], [inherited]
Definition at line 52 of file GaussianPrediction.h.
state_model_
std::unique_ptr<LinearStateModel> bfl::KFPrediction::state_model_ [private]
Definition at line 46 of file KFPrediction.h.
The documentation for this class was generated from the following files:
/home/user/bayes-filters-lib/src/BayesFilters/include/BayesFilters/KFPrediction.h
/home/user/bayes-filters-lib/src/BayesFilters/src/KFPrediction.cpp