bfl::LinearStateModel Class Reference
#include <LinearStateModel.h>
Public Member Functions
virtual ~LinearStateModel () noexcept=default
virtual void propagate (const Eigen::Ref< const Eigen::MatrixXd > &cur_states, Eigen::Ref< Eigen::MatrixXd > prop_states) override
virtual Eigen::MatrixXd getStateTransitionMatrix ()=0
virtual void motion (const Eigen::Ref< const Eigen::MatrixXd > &cur_states, Eigen::Ref< Eigen::MatrixXd > mot_states) override
virtual VectorDescription getInputDescription ()
Returns the vector description of the input to the state equation.
bool skip (const std::string &what_step, const bool status) override
bool is_skipping () override
bool add_exogenous_model (std::unique_ptr< ExogenousModel > exogenous_model)
bool have_exogenous_model () noexcept
ExogenousModel & exogenous_model ()
virtual Eigen::MatrixXd getJacobian ()
virtual Eigen::VectorXd getTransitionProbability (const Eigen::Ref< const Eigen::MatrixXd > &prev_states, const Eigen::Ref< const Eigen::MatrixXd > &cur_states)
virtual Eigen::MatrixXd getNoiseCovarianceMatrix ()
virtual Eigen::MatrixXd getNoiseSample (const std::size_t num)
virtual bool setSamplingTime (const double &time)
virtual bool setProperty (const std::string &property)=0
virtual VectorDescription getStateDescription ()=0
Returns the vector description of the output of the state equation.
Protected Member Functions
LinearStateModel () noexcept=default
LinearStateModel (const LinearStateModel &state_model) noexcept=delete
LinearStateModel & operator= (const LinearStateModel &state_model) noexcept=delete
LinearStateModel (LinearStateModel &&state_model) noexcept=default
LinearStateModel & operator= (LinearStateModel &&state_model) noexcept=default
Private Attributes
bool skip_ = false
Skip status.
std::unique_ptr< ExogenousModel > exogenous_model_
Exogenous model.
Detailed Description
Definition at line 18 of file LinearStateModel.h.
Constructor & Destructor Documentation
 LinearStateModel()
virtual bfl::LinearStateModel::~LinearStateModel () [virtual], [default], [noexcept]
LinearStateModel() [1/3]
bfl::LinearStateModel::LinearStateModel () [protected], [default], [noexcept]
LinearStateModel() [2/3]
bfl::LinearStateModel::LinearStateModel (const LinearStateModel & state_model) [protected], [delete], [noexcept]
LinearStateModel() [3/3]
bfl::LinearStateModel::LinearStateModel (LinearStateModel && state_model) [protected], [default], [noexcept]
Member Function Documentation
add_exogenous_model()
bool StateModel::add_exogenous_model (std::unique_ptr< ExogenousModel > exogenous_model) [inherited]
Definition at line 33 of file StateModel.cpp.
exogenous_model()
ExogenousModel & StateModel::exogenous_model () [inherited]
Definition at line 50 of file StateModel.cpp.
getInputDescription()
VectorDescription AdditiveStateModel::getInputDescription () [virtual], [inherited]
Returns the vector description of the input to the state equation.
Implements bfl::StateProcess.
Definition at line 22 of file AdditiveStateModel.cpp.
References bfl::VectorDescription::add_noise_components().
getJacobian()
Eigen::MatrixXd StateModel::getJacobian () [virtual], [inherited]
Reimplemented in bfl::LTIStateModel.
Definition at line 60 of file StateModel.cpp.
getNoiseCovarianceMatrix()
Eigen::MatrixXd StateModel::getNoiseCovarianceMatrix () [virtual], [inherited]
Reimplemented in bfl::WhiteNoiseAcceleration, and bfl::LTIStateModel.
Definition at line 72 of file StateModel.cpp.
Referenced by bfl::sigma_point::unscented_transform().
getNoiseSample()
Eigen::MatrixXd StateModel::getNoiseSample (const std::size_t num) [virtual], [inherited]
Reimplemented in bfl::WhiteNoiseAcceleration.
Definition at line 78 of file StateModel.cpp.
getStateDescription()
virtual VectorDescription bfl::StateProcess::getStateDescription () [pure virtual], [inherited]
Returns the vector description of the output of the state equation.
Implemented in bfl::WhiteNoiseAcceleration.
Referenced by bfl::sigma_point::unscented_transform().
getStateTransitionMatrix()
virtual Eigen::MatrixXd bfl::LinearStateModel::getStateTransitionMatrix () [pure virtual]
Implemented in bfl::WhiteNoiseAcceleration, and bfl::LTIStateModel.
getTransitionProbability()
Eigen::VectorXd StateModel::getTransitionProbability (const Eigen::Ref< const Eigen::MatrixXd > & prev_states, const Eigen::Ref< const Eigen::MatrixXd > & cur_states) [virtual], [inherited]
Reimplemented in bfl::WhiteNoiseAcceleration.
Definition at line 66 of file StateModel.cpp.
have_exogenous_model()
bool StateModel::have_exogenous_model () [noexcept], [inherited]
Definition at line 41 of file StateModel.cpp.
is_skipping()
bool StateModel::is_skipping () [override], [virtual], [inherited]
Implements bfl::Skippable.
Definition at line 27 of file StateModel.cpp.
motion()
void AdditiveStateModel::motion (const Eigen::Ref< const Eigen::MatrixXd > & cur_states, Eigen::Ref< Eigen::MatrixXd > mot_states) [override], [virtual], [inherited]
Implements bfl::StateProcess.
Definition at line 14 of file AdditiveStateModel.cpp.
operator=() [1/2]
LinearStateModel& bfl::LinearStateModel::operator= (const LinearStateModel & state_model) [protected], [delete], [noexcept]
operator=() [2/2]
LinearStateModel& bfl::LinearStateModel::operator= (LinearStateModel && state_model) [protected], [default], [noexcept]
propagate()
void LinearStateModel::propagate (const Eigen::Ref< const Eigen::MatrixXd > & cur_states, Eigen::Ref< Eigen::MatrixXd > prop_states) [override], [virtual]
Implements bfl::StateProcess.
Definition at line 16 of file LinearStateModel.cpp.
setProperty()
virtual bool bfl::StateProcess::setProperty (const std::string & property) [pure virtual], [inherited]
Implemented in bfl::WhiteNoiseAcceleration, and bfl::LTIStateModel.
setSamplingTime()
bool StateModel::setSamplingTime (const double & time) [virtual], [inherited]
Definition at line 84 of file StateModel.cpp.
skip()
bool StateModel::skip (const std::string & what_step, const bool status) [override], [virtual], [inherited]
Implements bfl::Skipper.
Definition at line 14 of file StateModel.cpp.
Member Data Documentation
exogenous_model_
std::unique_ptr<ExogenousModel> bfl::StateModel::exogenous_model_ [private], [inherited]
Exogenous model.
Definition at line 68 of file StateModel.h.
skip_
bool bfl::StateModel::skip_ = false [private], [inherited]
Skip status.
Definition at line 63 of file StateModel.h.
The documentation for this class was generated from the following files:
/home/user/bayes-filters-lib/src/BayesFilters/include/BayesFilters/LinearStateModel.h
/home/user/bayes-filters-lib/src/BayesFilters/src/LinearStateModel.cpp