bfl::TimeDecreasingDynamics Class Reference
#include <TimeDecreasingDynamics.h>
Classes
struct ImplData
Public Member Functions
TimeDecreasingDynamics (std::unique_ptr< StateModel > state_model, const unsigned int iterations) noexcept
TimeDecreasingDynamics (std::unique_ptr< StateModel > state_model, const double seconds) noexcept
TimeDecreasingDynamics (TimeDecreasingDynamics &&state_model) noexcept
virtual ~TimeDecreasingDynamics () noexcept
TimeDecreasingDynamics & operator= (TimeDecreasingDynamics &&state_model) noexcept
Eigen::MatrixXd getNoiseSample (const std::size_t num) override
bool setProperty (const std::string &property) override
Protected Attributes
std::unique_ptr< ImplData > pImpl_
Detailed Description
Definition at line 14 of file TimeDecreasingDynamics.h.
Constructor & Destructor Documentation
TimeDecreasingDynamics() [1/3]
TimeDecreasingDynamics::TimeDecreasingDynamics (std::unique_ptr< StateModel > state_model, const unsigned int iterations) [noexcept]
Definition at line 33 of file TimeDecreasingDynamics.cpp.
References bfl::TimeDecreasingDynamics::ImplData::iterations_, bfl::TimeDecreasingDynamics::ImplData::modality_, and bfl::TimeDecreasingDynamics::ImplData::seconds_.
TimeDecreasingDynamics() [2/3]
TimeDecreasingDynamics::TimeDecreasingDynamics (std::unique_ptr< StateModel > state_model, const double seconds) [noexcept]
Definition at line 48 of file TimeDecreasingDynamics.cpp.
References bfl::TimeDecreasingDynamics::ImplData::iterations_, bfl::TimeDecreasingDynamics::ImplData::modality_, and bfl::TimeDecreasingDynamics::ImplData::seconds_.
TimeDecreasingDynamics() [3/3]
TimeDecreasingDynamics::TimeDecreasingDynamics (TimeDecreasingDynamics && state_model) [noexcept]
Definition at line 70 of file TimeDecreasingDynamics.cpp.
 TimeDecreasingDynamics()
TimeDecreasingDynamics::~TimeDecreasingDynamics () [virtual], [noexcept]
Definition at line 76 of file TimeDecreasingDynamics.cpp.
Member Function Documentation
getNoiseSample()
MatrixXd TimeDecreasingDynamics::getNoiseSample (const std::size_t num) [override]
Definition at line 90 of file TimeDecreasingDynamics.cpp.
References bfl::TimeDecreasingDynamics::ImplData::current_iterations_, bfl::TimeDecreasingDynamics::ImplData::current_seconds_, bfl::TimeDecreasingDynamics::ImplData::iterations_, bfl::TimeDecreasingDynamics::ImplData::modality_, and bfl::TimeDecreasingDynamics::ImplData::seconds_.
operator=()
TimeDecreasingDynamics & TimeDecreasingDynamics::operator= (TimeDecreasingDynamics && state_model) [noexcept]
Definition at line 80 of file TimeDecreasingDynamics.cpp.
setProperty()
bool TimeDecreasingDynamics::setProperty (const std::string & property) [override]
Definition at line 121 of file TimeDecreasingDynamics.cpp.
References bfl::TimeDecreasingDynamics::ImplData::current_iterations_, bfl::TimeDecreasingDynamics::ImplData::current_seconds_, bfl::utils::CpuTimer< timetype >::elapsed(), bfl::utils::CpuTimer< timetype >::is_running(), bfl::TimeDecreasingDynamics::ImplData::modality_, bfl::utils::CpuTimer< timetype >::start(), bfl::utils::CpuTimer< timetype >::stop(), and bfl::TimeDecreasingDynamics::ImplData::timer_.
Member Data Documentation
pImpl_
std::unique_ptr<ImplData> bfl::TimeDecreasingDynamics::pImpl_ [protected]
Definition at line 32 of file TimeDecreasingDynamics.h.
The documentation for this class was generated from the following files:
/home/user/bayes-filters-lib/src/BayesFilters/include/BayesFilters/TimeDecreasingDynamics.h
/home/user/bayes-filters-lib/src/BayesFilters/src/TimeDecreasingDynamics.cpp