bfl::BootstrapCorrection Class Reference
#include <BootstrapCorrection.h>
Public Member Functions
BootstrapCorrection (std::unique_ptr< MeasurementModel > measurement_model, std::unique_ptr< LikelihoodModel > likelihood_model) noexcept
BootstrapCorrection (const BootstrapCorrection &correction) noexcept=delete
BootstrapCorrection & operator= (const BootstrapCorrection &correction) noexcept=delete
BootstrapCorrection (BootstrapCorrection &&correction) noexcept
BootstrapCorrection & operator= (BootstrapCorrection &&correction) noexcept
virtual ~BootstrapCorrection () noexcept=default
MeasurementModel & getMeasurementModel () noexcept override
LikelihoodModel & getLikelihoodModel () noexcept override
std::pair< bool, Eigen::VectorXd > getLikelihood () override
void correct (const ParticleSet &pred_particles, ParticleSet &cor_particles)
bool skip (const bool status) noexcept
bool freeze_measurements (const Data &data=Data())
Protected Member Functions
void correctStep (const ParticleSet &pred_particles, ParticleSet &cor_particles) override
Private Attributes
std::unique_ptr< MeasurementModel > measurement_model_
std::unique_ptr< LikelihoodModel > likelihood_model_
bool valid_likelihood_ = false
Eigen::VectorXd likelihood_
bool skip_ = false
Detailed Description
Definition at line 22 of file BootstrapCorrection.h.
Constructor & Destructor Documentation
BootstrapCorrection() [1/3]
BootstrapCorrection::BootstrapCorrection (std::unique_ptr< MeasurementModel > measurement_model, std::unique_ptr< LikelihoodModel > likelihood_model) [noexcept]
Definition at line 17 of file BootstrapCorrection.cpp.
BootstrapCorrection() [2/3]
bfl::BootstrapCorrection::BootstrapCorrection (const BootstrapCorrection & correction) [delete], [noexcept]
BootstrapCorrection() [3/3]
BootstrapCorrection::BootstrapCorrection (BootstrapCorrection && correction) [noexcept]
Definition at line 23 of file BootstrapCorrection.cpp.
 BootstrapCorrection()
virtual bfl::BootstrapCorrection::~BootstrapCorrection () [virtual], [default], [noexcept]
Member Function Documentation
correct()
void PFCorrection::correct (const ParticleSet & pred_particles, ParticleSet & cor_particles) [inherited]
Definition at line 14 of file PFCorrection.cpp.
correctStep()
void BootstrapCorrection::correctStep (const ParticleSet & pred_particles, ParticleSet & cor_particles) [override], [protected], [virtual]
Implements bfl::PFCorrection.
Definition at line 50 of file BootstrapCorrection.cpp.
References bfl::ParticleSet::state(), and bfl::GaussianMixture::weight().
freeze_measurements()
bool PFCorrection::freeze_measurements (const Data & data = Data()) [inherited]
Definition at line 32 of file PFCorrection.cpp.
getLikelihood()
std::pair< bool, VectorXd > BootstrapCorrection::getLikelihood () [override], [virtual]
Implements bfl::PFCorrection.
Definition at line 61 of file BootstrapCorrection.cpp.
getLikelihoodModel()
LikelihoodModel & BootstrapCorrection::getLikelihoodModel () [override], [virtual], [noexcept]
Implements bfl::PFCorrection.
Definition at line 44 of file BootstrapCorrection.cpp.
getMeasurementModel()
MeasurementModel & BootstrapCorrection::getMeasurementModel () [override], [virtual], [noexcept]
Implements bfl::PFCorrection.
Definition at line 38 of file BootstrapCorrection.cpp.
operator=() [1/2]
BootstrapCorrection & BootstrapCorrection::operator= (BootstrapCorrection && correction) [noexcept]
Definition at line 30 of file BootstrapCorrection.cpp.
References bfl::PFCorrection::operator=().
operator=() [2/2]
BootstrapCorrection& bfl::BootstrapCorrection::operator= (const BootstrapCorrection & correction) [delete], [noexcept]
skip()
bool PFCorrection::skip (const bool status) [noexcept], [inherited]
Definition at line 24 of file PFCorrection.cpp.
Member Data Documentation
likelihood_
Eigen::VectorXd bfl::BootstrapCorrection::likelihood_ [private]
Definition at line 55 of file BootstrapCorrection.h.
likelihood_model_
std::unique_ptr<LikelihoodModel> bfl::BootstrapCorrection::likelihood_model_ [private]
Definition at line 51 of file BootstrapCorrection.h.
measurement_model_
std::unique_ptr<MeasurementModel> bfl::BootstrapCorrection::measurement_model_ [private]
Definition at line 49 of file BootstrapCorrection.h.
skip_
bool bfl::PFCorrection::skip_ = false [private], [inherited]
Definition at line 58 of file PFCorrection.h.
valid_likelihood_
bool bfl::BootstrapCorrection::valid_likelihood_ = false [private]
Definition at line 53 of file BootstrapCorrection.h.
The documentation for this class was generated from the following files:
/home/user/bayes-filters-lib/src/BayesFilters/include/BayesFilters/BootstrapCorrection.h
/home/user/bayes-filters-lib/src/BayesFilters/src/BootstrapCorrection.cpp