bfl::ResamplingWithPrior Class Reference
#include <ResamplingWithPrior.h>
Public Member Functions
ResamplingWithPrior (std::unique_ptr< bfl::ParticleSetInitialization > init_model, const double prior_ratio, const unsigned int seed) noexcept
ResamplingWithPrior (std::unique_ptr< bfl::ParticleSetInitialization > init_model, const double prior_ratio) noexcept
ResamplingWithPrior (std::unique_ptr< bfl::ParticleSetInitialization > init_model) noexcept
ResamplingWithPrior (ResamplingWithPrior &&resampling) noexcept
virtual ~ResamplingWithPrior () noexcept=default
ResamplingWithPrior & operator= (ResamplingWithPrior &&resampling) noexcept
void resample (const ParticleSet &cor_particles, ParticleSet &res_particles, Eigen::Ref< Eigen::VectorXi > res_parents) override
virtual double neff (const Eigen::Ref< const Eigen::VectorXd > &cor_weights)
Protected Attributes
std::unique_ptr< bfl::ParticleSetInitialization > init_model_
double prior_ratio_ = 0.5
Private Member Functions
std::vector< unsigned int > sort_indices (const Eigen::Ref< const Eigen::VectorXd > &vector)
Private Attributes
std::mt19937_64 generator_
Detailed Description
Definition at line 25 of file ResamplingWithPrior.h.
Constructor & Destructor Documentation
ResamplingWithPrior() [1/4]
ResamplingWithPrior::ResamplingWithPrior (std::unique_ptr< bfl::ParticleSetInitialization > init_model, const double prior_ratio, const unsigned int seed) [noexcept]
Definition at line 19 of file ResamplingWithPrior.cpp.
ResamplingWithPrior() [2/4]
bfl::ResamplingWithPrior::ResamplingWithPrior (std::unique_ptr< bfl::ParticleSetInitialization > init_model, const double prior_ratio) [noexcept]
ResamplingWithPrior() [3/4]
bfl::ResamplingWithPrior::ResamplingWithPrior (std::unique_ptr< bfl::ParticleSetInitialization > init_model) [noexcept]
ResamplingWithPrior() [4/4]
ResamplingWithPrior::ResamplingWithPrior (ResamplingWithPrior && resampling) [noexcept]
Definition at line 39 of file ResamplingWithPrior.cpp.
 ResamplingWithPrior()
virtual bfl::ResamplingWithPrior::~ResamplingWithPrior () [virtual], [default], [noexcept]
Member Function Documentation
neff()
double Resampling::neff (const Eigen::Ref< const Eigen::VectorXd > & cor_weights) [virtual], [inherited]
Definition at line 97 of file Resampling.cpp.
operator=()
ResamplingWithPrior & ResamplingWithPrior::operator= (ResamplingWithPrior && resampling) [noexcept]
Definition at line 48 of file ResamplingWithPrior.cpp.
References bfl::Resampling::operator=().
resample()
void ResamplingWithPrior::resample (const ParticleSet & cor_particles, ParticleSet & res_particles, Eigen::Ref< Eigen::VectorXi > res_parents) [override], [virtual]
Reimplemented from bfl::Resampling.
Definition at line 61 of file ResamplingWithPrior.cpp.
References bfl::GaussianMixture::covariance(), bfl::GaussianMixture::dim_circular, bfl::GaussianMixture::dim_linear, bfl::utils::log_sum_exp(), bfl::GaussianMixture::mean(), bfl::Resampling::resample(), bfl::ParticleSet::state(), and bfl::GaussianMixture::weight().
sort_indices()
std::vector< unsigned int > ResamplingWithPrior::sort_indices (const Eigen::Ref< const Eigen::VectorXd > & vector) [private]
Definition at line 108 of file ResamplingWithPrior.cpp.
Member Data Documentation
generator_
std::mt19937_64 bfl::Resampling::generator_ [private], [inherited]
Definition at line 47 of file Resampling.h.
init_model_
std::unique_ptr<bfl::ParticleSetInitialization> bfl::ResamplingWithPrior::init_model_ [protected]
Definition at line 44 of file ResamplingWithPrior.h.
prior_ratio_
double bfl::ResamplingWithPrior::prior_ratio_ = 0.5 [protected]
Definition at line 46 of file ResamplingWithPrior.h.
The documentation for this class was generated from the following files:
/home/user/bayes-filters-lib/src/BayesFilters/include/BayesFilters/ResamplingWithPrior.h
/home/user/bayes-filters-lib/src/BayesFilters/src/ResamplingWithPrior.cpp