bfl::UKFCorrection Class Reference
#include <UKFCorrection.h>
Public Member Functions
UKFCorrection (std::unique_ptr< MeasurementModel > meas_model, const double alpha, const double beta, const double kappa, const bool update_weights_online=false) noexcept
UKFCorrection (std::unique_ptr< AdditiveMeasurementModel > meas_model, const double alpha, const double beta, const double kappa) noexcept
UKFCorrection (UKFCorrection &&ukf_prediction) noexcept
virtual ~UKFCorrection () noexcept=default
MeasurementModel & getMeasurementModel () override
std::pair< bool, Eigen::VectorXd > getLikelihood () override
void correct (const GaussianMixture &pred_state, GaussianMixture &corr_state)
bool skip (const bool status)
bool freeze_measurements (const Data &data=Data())
Protected Types
enum UKFCorrectionType { UKFCorrectionType::Generic,
UKFCorrectionType::Additive
 }
Protected Member Functions
void correctStep (const GaussianMixture &pred_state, GaussianMixture &corr_state) override
Protected Attributes
std::unique_ptr< MeasurementModel > measurement_model_
std::unique_ptr< AdditiveMeasurementModel > additive_measurement_model_
UKFCorrectionType type_
Distinguish between a UKFCorrection using a generic MeasurmentModel and a UKFCorrection using an AdditiveMeasurementModel.
sigma_point::UTWeight ut_weight_
Unscented transform weight.
const bool update_weights_online_ = false
The unscented transform for a generic non-additive measurement model requires the computation of 2 * n + 1 sigma points where n depends not only on the size of the input state but also on the size of the noise.
const double ut_alpha_
const double ut_beta_
const double ut_kappa_
Eigen::MatrixXd innovations_
GaussianMixture predicted_meas_
Private Attributes
bool skip_ = false
Detailed Description
Definition at line 24 of file UKFCorrection.h.
Member Enumeration Documentation
UKFCorrectionType
enum bfl::UKFCorrection::UKFCorrectionType [strong], [protected]
Enumerator
Generic
Additive
Definition at line 46 of file UKFCorrection.h.
Constructor & Destructor Documentation
UKFCorrection() [1/3]
UKFCorrection::UKFCorrection (std::unique_ptr< MeasurementModel > meas_model, const double alpha, const double beta, const double kappa, const bool update_weights_online = false) [noexcept]
Definition at line 17 of file UKFCorrection.cpp.
UKFCorrection() [2/3]
UKFCorrection::UKFCorrection (std::unique_ptr< AdditiveMeasurementModel > meas_model, const double alpha, const double beta, const double kappa) [noexcept]
Definition at line 35 of file UKFCorrection.cpp.
UKFCorrection() [3/3]
UKFCorrection::UKFCorrection (UKFCorrection && ukf_prediction) [noexcept]
Definition at line 50 of file UKFCorrection.cpp.
 UKFCorrection()
virtual bfl::UKFCorrection::~UKFCorrection () [virtual], [default], [noexcept]
Member Function Documentation
correct()
void GaussianCorrection::correct (const GaussianMixture & pred_state, GaussianMixture & corr_state) [inherited]
Definition at line 16 of file GaussianCorrection.cpp.
correctStep()
void UKFCorrection::correctStep (const GaussianMixture & pred_state, GaussianMixture & corr_state) [override], [protected], [virtual]
Implements bfl::GaussianCorrection.
Definition at line 86 of file UKFCorrection.cpp.
References bfl::GaussianMixture::augmentWithNoise(), bfl::GaussianMixture::components, bfl::GaussianMixture::covariance(), bfl::MeasurementModel::getMeasurementDescription(), bfl::MeasurementModel::getNoiseCovarianceMatrix(), bfl::MeasurementModel::innovation(), bfl::GaussianMixture::mean(), bfl::MeasurementModel::measure(), bfl::VectorDescription::total_size(), and bfl::sigma_point::unscented_transform().
freeze_measurements()
bool GaussianCorrection::freeze_measurements (const Data & data = Data()) [inherited]
Definition at line 34 of file GaussianCorrection.cpp.
getLikelihood()
std::pair< bool, VectorXd > UKFCorrection::getLikelihood () [override], [virtual]
Reimplemented from bfl::GaussianCorrection.
Definition at line 71 of file UKFCorrection.cpp.
References bfl::utils::multivariate_gaussian_density().
getMeasurementModel()
MeasurementModel & UKFCorrection::getMeasurementModel () [override], [virtual]
Implements bfl::GaussianCorrection.
Definition at line 62 of file UKFCorrection.cpp.
skip()
bool GaussianCorrection::skip (const bool status) [inherited]
Definition at line 26 of file GaussianCorrection.cpp.
Member Data Documentation
additive_measurement_model_
std::unique_ptr<AdditiveMeasurementModel> bfl::UKFCorrection::additive_measurement_model_ [protected]
Definition at line 44 of file UKFCorrection.h.
innovations_
Eigen::MatrixXd bfl::UKFCorrection::innovations_ [protected]
Definition at line 74 of file UKFCorrection.h.
measurement_model_
std::unique_ptr<MeasurementModel> bfl::UKFCorrection::measurement_model_ [protected]
Definition at line 42 of file UKFCorrection.h.
predicted_meas_
GaussianMixture bfl::UKFCorrection::predicted_meas_ [protected]
Definition at line 76 of file UKFCorrection.h.
skip_
bool bfl::GaussianCorrection::skip_ = false [private], [inherited]
Definition at line 52 of file GaussianCorrection.h.
type_
UKFCorrectionType bfl::UKFCorrection::type_ [protected]
Distinguish between a UKFCorrection using a generic MeasurmentModel and a UKFCorrection using an AdditiveMeasurementModel.
Definition at line 52 of file UKFCorrection.h.
update_weights_online_
const bool bfl::UKFCorrection::update_weights_online_ = false [protected]
The unscented transform for a generic non-additive measurement model requires the computation of 2 * n + 1 sigma points where n depends not only on the size of the input state but also on the size of the noise.
While the state size is fixed, the noise size might depend on the number of measurements available, hence n might change online. Since the unscented transform weights, stored in ut_weight_, depend on n the user can specify, using the ctor input parameter update_weights_online, that the weights have to be re-computed at each iteration.
Definition at line 66 of file UKFCorrection.h.
ut_alpha_
const double bfl::UKFCorrection::ut_alpha_ [protected]
Definition at line 68 of file UKFCorrection.h.
ut_beta_
const double bfl::UKFCorrection::ut_beta_ [protected]
Definition at line 70 of file UKFCorrection.h.
ut_kappa_
const double bfl::UKFCorrection::ut_kappa_ [protected]
Definition at line 72 of file UKFCorrection.h.
ut_weight_
sigma_point::UTWeight bfl::UKFCorrection::ut_weight_ [protected]
Unscented transform weight.
Definition at line 57 of file UKFCorrection.h.
The documentation for this class was generated from the following files:
/home/user/bayes-filters-lib/src/BayesFilters/include/BayesFilters/UKFCorrection.h
/home/user/bayes-filters-lib/src/BayesFilters/src/UKFCorrection.cpp