bfl::GPFPrediction Class Reference
#include <GPFPrediction.h>
Public Member Functions
GPFPrediction (std::unique_ptr< GaussianPrediction > gauss_prediction) noexcept
GPFPrediction (const GPFPrediction &prediction) noexcept=delete
GPFPrediction & operator= (const GPFPrediction &prediction) noexcept=delete
GPFPrediction (GPFPrediction &&prediction) noexcept
GPFPrediction & operator= (GPFPrediction &&prediction) noexcept
virtual ~GPFPrediction () noexcept=default
StateModel & getStateModel () noexcept override
void predict (const ParticleSet &prev_particles, ParticleSet &pred_particles)
bool skip (const std::string &what_step, const bool status)
bool is_skipping ()
Protected Member Functions
void predictStep (const ParticleSet &previous_particles, ParticleSet &predicted_particles) override
Private Attributes
std::unique_ptr< GaussianPrediction > gaussian_prediction_
bool skip_ = false
Detailed Description
Definition at line 24 of file GPFPrediction.h.
Constructor & Destructor Documentation
GPFPrediction() [1/3]
GPFPrediction::GPFPrediction (std::unique_ptr< GaussianPrediction > gauss_prediction) [noexcept]
Definition at line 16 of file GPFPrediction.cpp.
GPFPrediction() [2/3]
bfl::GPFPrediction::GPFPrediction (const GPFPrediction & prediction) [delete], [noexcept]
GPFPrediction() [3/3]
GPFPrediction::GPFPrediction (GPFPrediction && prediction) [noexcept]
Definition at line 21 of file GPFPrediction.cpp.
 GPFPrediction()
virtual bfl::GPFPrediction::~GPFPrediction () [virtual], [default], [noexcept]
Member Function Documentation
getStateModel()
StateModel & GPFPrediction::getStateModel () [override], [virtual], [noexcept]
Implements bfl::PFPrediction.
Definition at line 40 of file GPFPrediction.cpp.
is_skipping()
bool PFPrediction::is_skipping () [inherited]
Definition at line 55 of file PFPrediction.cpp.
operator=() [1/2]
GPFPrediction& bfl::GPFPrediction::operator= (const GPFPrediction & prediction) [delete], [noexcept]
operator=() [2/2]
GPFPrediction & GPFPrediction::operator= (GPFPrediction && prediction) [noexcept]
Definition at line 27 of file GPFPrediction.cpp.
References bfl::PFPrediction::operator=().
predict()
void PFPrediction::predict (const ParticleSet & prev_particles, ParticleSet & pred_particles) [inherited]
Definition at line 17 of file PFPrediction.cpp.
predictStep()
void GPFPrediction::predictStep (const ParticleSet & previous_particles, ParticleSet & predicted_particles) [override], [protected], [virtual]
Implements bfl::PFPrediction.
Definition at line 46 of file GPFPrediction.cpp.
References bfl::ParticleSet::state(), and bfl::GaussianMixture::weight().
skip()
bool PFPrediction::skip (const std::string & what_step, const bool status) [inherited]
Definition at line 26 of file PFPrediction.cpp.
Member Data Documentation
gaussian_prediction_
std::unique_ptr<GaussianPrediction> bfl::GPFPrediction::gaussian_prediction_ [private]
Definition at line 47 of file GPFPrediction.h.
skip_
bool bfl::PFPrediction::skip_ = false [private], [inherited]
Definition at line 54 of file PFPrediction.h.
The documentation for this class was generated from the following files:
/home/user/bayes-filters-lib/src/BayesFilters/include/BayesFilters/GPFPrediction.h
/home/user/bayes-filters-lib/src/BayesFilters/src/GPFPrediction.cpp