bfl::GPFCorrection Class Reference
#include <GPFCorrection.h>
Public Member Functions
GPFCorrection (std::unique_ptr< LikelihoodModel > likelihood_model, std::unique_ptr< GaussianCorrection > gaussian_correction, std::unique_ptr< StateModel > state_model) noexcept
GPFCorrection (std::unique_ptr< LikelihoodModel > likelihood_model, std::unique_ptr< GaussianCorrection > gaussian_correction, std::unique_ptr< StateModel > state_model, unsigned int seed) noexcept
GPFCorrection (const GPFCorrection &correction) noexcept=delete
GPFCorrection & operator= (const GPFCorrection &correction) noexcept=delete
GPFCorrection (GPFCorrection &&correction) noexcept
GPFCorrection & operator= (GPFCorrection &&correction) noexcept
virtual ~GPFCorrection () noexcept=default
MeasurementModel & getMeasurementModel () noexcept override
LikelihoodModel & getLikelihoodModel () noexcept override
std::pair< bool, Eigen::VectorXd > getLikelihood () override
void correct (const ParticleSet &pred_particles, ParticleSet &cor_particles)
bool skip (const bool status) noexcept
bool freeze_measurements (const Data &data=Data())
Protected Member Functions
void correctStep (const ParticleSet &pred_particles, ParticleSet &corr_particles) override
Eigen::VectorXd sampleFromProposal (const Eigen::VectorXd &mean, const Eigen::MatrixXd &covariance)
double evaluateProposal (const Eigen::VectorXd &state, const Eigen::VectorXd &mean, const Eigen::MatrixXd &covariance)
Protected Attributes
std::function< double()> gaussian_random_sample_
Random number generator function from a Normal distribution.
Private Attributes
std::unique_ptr< LikelihoodModel > likelihood_model_
std::unique_ptr< GaussianCorrection > gaussian_correction_
std::unique_ptr< StateModel > state_model_
The state model is required to evaluate the Markov transition probability that is used in the update of the particles weight.
std::mt19937_64 generator_
std::normal_distribution< double > distribution_
bool valid_likelihood_
Eigen::VectorXd likelihood_
bool skip_ = false
Detailed Description
Definition at line 27 of file GPFCorrection.h.
Constructor & Destructor Documentation
GPFCorrection() [1/4]
GPFCorrection::GPFCorrection (std::unique_ptr< LikelihoodModel > likelihood_model, std::unique_ptr< GaussianCorrection > gaussian_correction, std::unique_ptr< StateModel > state_model) [noexcept]
Definition at line 20 of file GPFCorrection.cpp.
GPFCorrection() [2/4]
GPFCorrection::GPFCorrection (std::unique_ptr< LikelihoodModel > likelihood_model, std::unique_ptr< GaussianCorrection > gaussian_correction, std::unique_ptr< StateModel > state_model, unsigned int seed) [noexcept]
Definition at line 30 of file GPFCorrection.cpp.
GPFCorrection() [3/4]
bfl::GPFCorrection::GPFCorrection (const GPFCorrection & correction) [delete], [noexcept]
GPFCorrection() [4/4]
GPFCorrection::GPFCorrection (GPFCorrection && correction) [noexcept]
Definition at line 45 of file GPFCorrection.cpp.
 GPFCorrection()
virtual bfl::GPFCorrection::~GPFCorrection () [virtual], [default], [noexcept]
Member Function Documentation
correct()
void PFCorrection::correct (const ParticleSet & pred_particles, ParticleSet & cor_particles) [inherited]
Definition at line 14 of file PFCorrection.cpp.
correctStep()
void GPFCorrection::correctStep (const ParticleSet & pred_particles, bfl::ParticleSet & corr_particles) [override], [protected], [virtual]
Implements bfl::PFCorrection.
Definition at line 98 of file GPFCorrection.cpp.
References bfl::GaussianMixture::components, bfl::GaussianMixture::covariance(), bfl::GaussianMixture::mean(), bfl::ParticleSet::state(), and bfl::GaussianMixture::weight().
evaluateProposal()
double GPFCorrection::evaluateProposal (const Eigen::VectorXd & state, const Eigen::VectorXd & mean, const Eigen::MatrixXd & covariance) [protected]
Definition at line 153 of file GPFCorrection.cpp.
References bfl::utils::multivariate_gaussian_density().
freeze_measurements()
bool PFCorrection::freeze_measurements (const Data & data = Data()) [inherited]
Definition at line 32 of file PFCorrection.cpp.
getLikelihood()
std::pair< bool, Eigen::VectorXd > GPFCorrection::getLikelihood () [override], [virtual]
Implements bfl::PFCorrection.
Definition at line 92 of file GPFCorrection.cpp.
getLikelihoodModel()
LikelihoodModel & GPFCorrection::getLikelihoodModel () [override], [virtual], [noexcept]
Implements bfl::PFCorrection.
Definition at line 86 of file GPFCorrection.cpp.
getMeasurementModel()
MeasurementModel & GPFCorrection::getMeasurementModel () [override], [virtual], [noexcept]
Implements bfl::PFCorrection.
Definition at line 80 of file GPFCorrection.cpp.
operator=() [1/2]
GPFCorrection& bfl::GPFCorrection::operator= (const GPFCorrection & correction) [delete], [noexcept]
operator=() [2/2]
GPFCorrection & GPFCorrection::operator= (GPFCorrection && correction) [noexcept]
Definition at line 58 of file GPFCorrection.cpp.
References bfl::PFCorrection::operator=().
sampleFromProposal()
Eigen::VectorXd GPFCorrection::sampleFromProposal (const Eigen::VectorXd & mean, const Eigen::MatrixXd & covariance) [protected]
Definition at line 133 of file GPFCorrection.cpp.
skip()
bool PFCorrection::skip (const bool status) [noexcept], [inherited]
Definition at line 24 of file PFCorrection.cpp.
Member Data Documentation
distribution_
std::normal_distribution<double> bfl::GPFCorrection::distribution_ [private]
Definition at line 77 of file GPFCorrection.h.
gaussian_correction_
std::unique_ptr<GaussianCorrection> bfl::GPFCorrection::gaussian_correction_ [private]
Definition at line 67 of file GPFCorrection.h.
gaussian_random_sample_
std::function<double()> bfl::GPFCorrection::gaussian_random_sample_ [protected]
Random number generator function from a Normal distribution.
A call to gaussian_random_sample_() returns a double-precision floating-point random number.
Definition at line 62 of file GPFCorrection.h.
generator_
std::mt19937_64 bfl::GPFCorrection::generator_ [private]
Definition at line 75 of file GPFCorrection.h.
likelihood_
Eigen::VectorXd bfl::GPFCorrection::likelihood_ [private]
Definition at line 81 of file GPFCorrection.h.
likelihood_model_
std::unique_ptr<LikelihoodModel> bfl::GPFCorrection::likelihood_model_ [private]
Definition at line 65 of file GPFCorrection.h.
skip_
bool bfl::PFCorrection::skip_ = false [private], [inherited]
Definition at line 58 of file PFCorrection.h.
state_model_
std::unique_ptr<StateModel> bfl::GPFCorrection::state_model_ [private]
The state model is required to evaluate the Markov transition probability that is used in the update of the particles weight.
Definition at line 73 of file GPFCorrection.h.
valid_likelihood_
bool bfl::GPFCorrection::valid_likelihood_ [private]
Definition at line 79 of file GPFCorrection.h.
The documentation for this class was generated from the following files:
/home/user/bayes-filters-lib/src/BayesFilters/include/BayesFilters/GPFCorrection.h
/home/user/bayes-filters-lib/src/BayesFilters/src/GPFCorrection.cpp