bfl::DrawParticles Class Reference
#include <DrawParticles.h>
Public Member Functions
DrawParticles (std::unique_ptr< StateModel > state_model) noexcept
DrawParticles (std::unique_ptr< StateModel > state_model, std::unique_ptr< ExogenousModel > exogenous_model) noexcept
DrawParticles (const DrawParticles &prediction) noexcept=delete
DrawParticles & operator= (const DrawParticles &prediction) noexcept=delete
DrawParticles (DrawParticles &&prediction) noexcept
DrawParticles & operator= (DrawParticles &&prediction) noexcept
virtual ~DrawParticles () noexcept=default
StateModel & getStateModel () noexcept override
void predict (const ParticleSet &prev_particles, ParticleSet &pred_particles)
bool skip (const std::string &what_step, const bool status)
bool is_skipping ()
Protected Member Functions
void predictStep (const ParticleSet &prev_particles, ParticleSet &pred_particles) override
Protected Attributes
std::unique_ptr< StateModel > state_model_
std::unique_ptr< ExogenousModel > exogenous_model_
Private Attributes
bool skip_ = false
Detailed Description
Definition at line 19 of file DrawParticles.h.
Constructor & Destructor Documentation
DrawParticles() [1/4]
DrawParticles::DrawParticles (std::unique_ptr< StateModel > state_model) [noexcept]
Definition at line 16 of file DrawParticles.cpp.
DrawParticles() [2/4]
DrawParticles::DrawParticles (std::unique_ptr< StateModel > state_model, std::unique_ptr< ExogenousModel > exogenous_model) [noexcept]
Definition at line 21 of file DrawParticles.cpp.
DrawParticles() [3/4]
bfl::DrawParticles::DrawParticles (const DrawParticles & prediction) [delete], [noexcept]
DrawParticles() [4/4]
DrawParticles::DrawParticles (DrawParticles && prediction) [noexcept]
Definition at line 27 of file DrawParticles.cpp.
 DrawParticles()
virtual bfl::DrawParticles::~DrawParticles () [virtual], [default], [noexcept]
Member Function Documentation
getStateModel()
StateModel & DrawParticles::getStateModel () [override], [virtual], [noexcept]
Implements bfl::PFPrediction.
Definition at line 46 of file DrawParticles.cpp.
is_skipping()
bool PFPrediction::is_skipping () [inherited]
Definition at line 55 of file PFPrediction.cpp.
operator=() [1/2]
DrawParticles& bfl::DrawParticles::operator= (const DrawParticles & prediction) [delete], [noexcept]
operator=() [2/2]
DrawParticles & DrawParticles::operator= (DrawParticles && prediction) [noexcept]
Definition at line 34 of file DrawParticles.cpp.
References bfl::PFPrediction::operator=().
predict()
void PFPrediction::predict (const ParticleSet & prev_particles, ParticleSet & pred_particles) [inherited]
Definition at line 17 of file PFPrediction.cpp.
predictStep()
void DrawParticles::predictStep (const ParticleSet & prev_particles, ParticleSet & pred_particles) [override], [protected], [virtual]
Implements bfl::PFPrediction.
Definition at line 52 of file DrawParticles.cpp.
References bfl::ParticleSet::state(), and bfl::GaussianMixture::weight().
skip()
bool PFPrediction::skip (const std::string & what_step, const bool status) [inherited]
Definition at line 26 of file PFPrediction.cpp.
Member Data Documentation
exogenous_model_
std::unique_ptr<ExogenousModel> bfl::DrawParticles::exogenous_model_ [protected]
Definition at line 44 of file DrawParticles.h.
skip_
bool bfl::PFPrediction::skip_ = false [private], [inherited]
Definition at line 54 of file PFPrediction.h.
state_model_
std::unique_ptr<StateModel> bfl::DrawParticles::state_model_ [protected]
Definition at line 42 of file DrawParticles.h.
The documentation for this class was generated from the following files:
/home/user/bayes-filters-lib/src/BayesFilters/include/BayesFilters/DrawParticles.h
/home/user/bayes-filters-lib/src/BayesFilters/src/DrawParticles.cpp