bfl::StateModel Class Reference
#include <StateModel.h>
Public Member Functions
virtual ~StateModel () noexcept=default
bool skip (const std::string &what_step, const bool status) override
bool is_skipping () override
bool add_exogenous_model (std::unique_ptr< ExogenousModel > exogenous_model)
bool have_exogenous_model () noexcept
ExogenousModel & exogenous_model ()
virtual Eigen::MatrixXd getJacobian ()
virtual Eigen::VectorXd getTransitionProbability (const Eigen::Ref< const Eigen::MatrixXd > &prev_states, const Eigen::Ref< const Eigen::MatrixXd > &cur_states)
virtual Eigen::MatrixXd getNoiseCovarianceMatrix ()
virtual Eigen::MatrixXd getNoiseSample (const std::size_t num)
virtual bool setSamplingTime (const double &time)
virtual void propagate (const Eigen::Ref< const Eigen::MatrixXd > &cur_states, Eigen::Ref< Eigen::MatrixXd > prop_states)=0
virtual void motion (const Eigen::Ref< const Eigen::MatrixXd > &cur_states, Eigen::Ref< Eigen::MatrixXd > mot_states)=0
virtual bool setProperty (const std::string &property)=0
virtual VectorDescription getInputDescription ()=0
Returns the vector description of the input to the state equation.
virtual VectorDescription getStateDescription ()=0
Returns the vector description of the output of the state equation.
Protected Member Functions
StateModel () noexcept=default
StateModel (const StateModel &state_model) noexcept=delete
StateModel & operator= (const StateModel &state_model) noexcept=delete
StateModel (StateModel &&state_model) noexcept=default
StateModel & operator= (StateModel &&state_model) noexcept=default
Private Attributes
bool skip_ = false
Skip status.
std::unique_ptr< ExogenousModel > exogenous_model_
Exogenous model.
Detailed Description
Definition at line 22 of file StateModel.h.
Constructor & Destructor Documentation
 StateModel()
virtual bfl::StateModel::~StateModel () [virtual], [default], [noexcept]
StateModel() [1/3]
bfl::StateModel::StateModel () [protected], [default], [noexcept]
StateModel() [2/3]
bfl::StateModel::StateModel (const StateModel & state_model) [protected], [delete], [noexcept]
StateModel() [3/3]
bfl::StateModel::StateModel (StateModel && state_model) [protected], [default], [noexcept]
Member Function Documentation
add_exogenous_model()
bool StateModel::add_exogenous_model (std::unique_ptr< ExogenousModel > exogenous_model)
Definition at line 33 of file StateModel.cpp.
exogenous_model()
ExogenousModel & StateModel::exogenous_model ()
Definition at line 50 of file StateModel.cpp.
getInputDescription()
virtual VectorDescription bfl::StateProcess::getInputDescription () [pure virtual], [inherited]
Returns the vector description of the input to the state equation.
Implemented in bfl::AdditiveStateModel.
getJacobian()
Eigen::MatrixXd StateModel::getJacobian () [virtual]
Reimplemented in bfl::LTIStateModel.
Definition at line 60 of file StateModel.cpp.
getNoiseCovarianceMatrix()
Eigen::MatrixXd StateModel::getNoiseCovarianceMatrix () [virtual]
Reimplemented in bfl::WhiteNoiseAcceleration, and bfl::LTIStateModel.
Definition at line 72 of file StateModel.cpp.
Referenced by bfl::sigma_point::unscented_transform().
getNoiseSample()
Eigen::MatrixXd StateModel::getNoiseSample (const std::size_t num) [virtual]
Reimplemented in bfl::WhiteNoiseAcceleration.
Definition at line 78 of file StateModel.cpp.
getStateDescription()
virtual VectorDescription bfl::StateProcess::getStateDescription () [pure virtual], [inherited]
Returns the vector description of the output of the state equation.
Implemented in bfl::WhiteNoiseAcceleration.
Referenced by bfl::sigma_point::unscented_transform().
getTransitionProbability()
Eigen::VectorXd StateModel::getTransitionProbability (const Eigen::Ref< const Eigen::MatrixXd > & prev_states, const Eigen::Ref< const Eigen::MatrixXd > & cur_states) [virtual]
Reimplemented in bfl::WhiteNoiseAcceleration.
Definition at line 66 of file StateModel.cpp.
have_exogenous_model()
bool StateModel::have_exogenous_model () [noexcept]
Definition at line 41 of file StateModel.cpp.
is_skipping()
bool StateModel::is_skipping () [override], [virtual]
Implements bfl::Skippable.
Definition at line 27 of file StateModel.cpp.
motion()
virtual void bfl::StateProcess::motion (const Eigen::Ref< const Eigen::MatrixXd > & cur_states, Eigen::Ref< Eigen::MatrixXd > mot_states) [pure virtual], [inherited]
Implemented in bfl::AdditiveStateModel.
Referenced by bfl::sigma_point::unscented_transform().
operator=() [1/2]
StateModel& bfl::StateModel::operator= (const StateModel & state_model) [protected], [delete], [noexcept]
operator=() [2/2]
StateModel& bfl::StateModel::operator= (StateModel && state_model) [protected], [default], [noexcept]
propagate()
virtual void bfl::StateProcess::propagate (const Eigen::Ref< const Eigen::MatrixXd > & cur_states, Eigen::Ref< Eigen::MatrixXd > prop_states) [pure virtual], [inherited]
Implemented in bfl::LinearStateModel.
Referenced by bfl::sigma_point::unscented_transform().
setProperty()
virtual bool bfl::StateProcess::setProperty (const std::string & property) [pure virtual], [inherited]
Implemented in bfl::WhiteNoiseAcceleration, and bfl::LTIStateModel.
setSamplingTime()
bool StateModel::setSamplingTime (const double & time) [virtual]
Definition at line 84 of file StateModel.cpp.
skip()
bool StateModel::skip (const std::string & what_step, const bool status) [override], [virtual]
Implements bfl::Skipper.
Definition at line 14 of file StateModel.cpp.
Member Data Documentation
exogenous_model_
std::unique_ptr<ExogenousModel> bfl::StateModel::exogenous_model_ [private]
Exogenous model.
Definition at line 68 of file StateModel.h.
skip_
bool bfl::StateModel::skip_ = false [private]
Skip status.
Definition at line 63 of file StateModel.h.
The documentation for this class was generated from the following files:
/home/user/bayes-filters-lib/src/BayesFilters/include/BayesFilters/StateModel.h
/home/user/bayes-filters-lib/src/BayesFilters/src/StateModel.cpp