bfl::StateProcess Class Reference
#include <StateProcess.h>
Public Member Functions
virtual void propagate (const Eigen::Ref< const Eigen::MatrixXd > &cur_states, Eigen::Ref< Eigen::MatrixXd > prop_states)=0
virtual void motion (const Eigen::Ref< const Eigen::MatrixXd > &cur_states, Eigen::Ref< Eigen::MatrixXd > mot_states)=0
virtual bool setProperty (const std::string &property)=0
virtual VectorDescription getInputDescription ()=0
Returns the vector description of the input to the state equation.
virtual VectorDescription getStateDescription ()=0
Returns the vector description of the output of the state equation.
Detailed Description
Definition at line 20 of file StateProcess.h.
Member Function Documentation
getInputDescription()
virtual VectorDescription bfl::StateProcess::getInputDescription () [pure virtual]
Returns the vector description of the input to the state equation.
Implemented in bfl::AdditiveStateModel.
getStateDescription()
virtual VectorDescription bfl::StateProcess::getStateDescription () [pure virtual]
Returns the vector description of the output of the state equation.
Implemented in bfl::WhiteNoiseAcceleration.
Referenced by bfl::sigma_point::unscented_transform().
motion()
virtual void bfl::StateProcess::motion (const Eigen::Ref< const Eigen::MatrixXd > & cur_states, Eigen::Ref< Eigen::MatrixXd > mot_states) [pure virtual]
Implemented in bfl::AdditiveStateModel.
Referenced by bfl::sigma_point::unscented_transform().
propagate()
virtual void bfl::StateProcess::propagate (const Eigen::Ref< const Eigen::MatrixXd > & cur_states, Eigen::Ref< Eigen::MatrixXd > prop_states) [pure virtual]
Implemented in bfl::LinearStateModel.
Referenced by bfl::sigma_point::unscented_transform().
setProperty()
virtual bool bfl::StateProcess::setProperty (const std::string & property) [pure virtual]
Implemented in bfl::WhiteNoiseAcceleration, and bfl::LTIStateModel.
The documentation for this class was generated from the following file:
/home/user/bayes-filters-lib/src/BayesFilters/include/BayesFilters/StateProcess.h