bfl::Resampling Class Reference
#include <Resampling.h>
Public Member Functions
Resampling (unsigned int seed) noexcept
Resampling () noexcept
Resampling (const Resampling &resampling) noexcept
Resampling (Resampling &&resampling) noexcept
virtual ~Resampling () noexcept=default
Resampling & operator= (const Resampling &resampling)
Resampling & operator= (Resampling &&resampling) noexcept
Resampling & operator= (const Resampling &&resampling) noexcept
virtual void resample (const bfl::ParticleSet &cor_particles, bfl::ParticleSet &res_particles, Eigen::Ref< Eigen::VectorXi > res_parents)
virtual double neff (const Eigen::Ref< const Eigen::VectorXd > &cor_weights)
Private Attributes
std::mt19937_64 generator_
Detailed Description
Definition at line 22 of file Resampling.h.
Constructor & Destructor Documentation
Resampling() [1/4]
Resampling::Resampling (unsigned int seed) [noexcept]
Definition at line 16 of file Resampling.cpp.
Resampling() [2/4]
Resampling::Resampling () [noexcept]
Definition at line 21 of file Resampling.cpp.
Resampling() [3/4]
Resampling::Resampling (const Resampling & resampling) [noexcept]
Definition at line 26 of file Resampling.cpp.
Resampling() [4/4]
Resampling::Resampling (Resampling && resampling) [noexcept]
Definition at line 31 of file Resampling.cpp.
 Resampling()
virtual bfl::Resampling::~Resampling () [virtual], [default], [noexcept]
Member Function Documentation
neff()
double Resampling::neff (const Eigen::Ref< const Eigen::VectorXd > & cor_weights) [virtual]
Definition at line 97 of file Resampling.cpp.
operator=() [1/3]
Resampling & Resampling::operator= (const Resampling && resampling) [noexcept]
Definition at line 56 of file Resampling.cpp.
operator=() [2/3]
Resampling & Resampling::operator= (const Resampling & resampling)
Definition at line 36 of file Resampling.cpp.
Referenced by bfl::ResamplingWithPrior::operator=().
operator=() [3/3]
Resampling & Resampling::operator= (Resampling && resampling) [noexcept]
Definition at line 45 of file Resampling.cpp.
resample()
void Resampling::resample (const bfl::ParticleSet & cor_particles, bfl::ParticleSet & res_particles, Eigen::Ref< Eigen::VectorXi > res_parents) [virtual]
Reimplemented in bfl::ResamplingWithPrior.
Definition at line 67 of file Resampling.cpp.
References bfl::GaussianMixture::covariance(), bfl::GaussianMixture::mean(), bfl::ParticleSet::state(), and bfl::GaussianMixture::weight().
Referenced by bfl::ResamplingWithPrior::resample().
Member Data Documentation
generator_
std::mt19937_64 bfl::Resampling::generator_ [private]
Definition at line 47 of file Resampling.h.
The documentation for this class was generated from the following files:
/home/user/bayes-filters-lib/src/BayesFilters/include/BayesFilters/Resampling.h
/home/user/bayes-filters-lib/src/BayesFilters/src/Resampling.cpp