bfl::GaussianMixture Class Reference
#include <GaussianMixture.h>
Public Member Functions
GaussianMixture () noexcept
GaussianMixture (const std::size_t components, const std::size_t dim) noexcept
GaussianMixture (const std::size_t components, const std::size_t dim_linear, const std::size_t dim_circular, const bool use_quaternion=false) noexcept
virtual ~GaussianMixture () noexcept=default
virtual void resize (const std::size_t components, const std::size_t dim_linear, const std::size_t dim_circular=0)
Eigen::Ref< Eigen::MatrixXd > mean ()
Eigen::Ref< Eigen::VectorXd > mean (const std::size_t i)
double & mean (const std::size_t i, const std::size_t j)
const Eigen::Ref< const Eigen::MatrixXd > mean () const
const Eigen::Ref< const Eigen::VectorXd > mean (const std::size_t i) const
const double & mean (const std::size_t i, const std::size_t j) const
Eigen::Ref< Eigen::MatrixXd > covariance ()
Eigen::Ref< Eigen::MatrixXd > covariance (const std::size_t i)
double & covariance (const std::size_t i, const std::size_t j, const std::size_t k)
const Eigen::Ref< const Eigen::MatrixXd > covariance () const
const Eigen::Ref< const Eigen::MatrixXd > covariance (const std::size_t i) const
const double & covariance (const std::size_t i, const std::size_t j, const std::size_t k) const
Eigen::Ref< Eigen::VectorXd > weight ()
double & weight (const std::size_t i)
const Eigen::Ref< const Eigen::VectorXd > weight () const
const double & weight (const std::size_t i) const
bool augmentWithNoise (const Eigen::Ref< const Eigen::MatrixXd > &noise_covariance_matrix)
Public Attributes
std::size_t components
bool use_quaternion
std::size_t dim_circular_component
std::size_t dim
std::size_t dim_linear
std::size_t dim_circular
std::size_t dim_noise
std::size_t dim_covariance
Protected Attributes
Eigen::MatrixXd mean_
Eigen::MatrixXd covariance_
Eigen::VectorXd weight_
Detailed Description
Definition at line 20 of file GaussianMixture.h.
Constructor & Destructor Documentation
GaussianMixture() [1/3]
GaussianMixture::GaussianMixture () [noexcept]
Definition at line 14 of file GaussianMixture.cpp.
GaussianMixture() [2/3]
GaussianMixture::GaussianMixture (const std::size_t components, const std::size_t dim) [noexcept]
Definition at line 19 of file GaussianMixture.cpp.
GaussianMixture() [3/3]
GaussianMixture::GaussianMixture (const std::size_t components, const std::size_t dim_linear, const std::size_t dim_circular, const bool use_quaternion = false) [noexcept]
Definition at line 25 of file GaussianMixture.cpp.
 GaussianMixture()
virtual bfl::GaussianMixture::~GaussianMixture () [virtual], [default], [noexcept]
Member Function Documentation
augmentWithNoise()
bool GaussianMixture::augmentWithNoise (const Eigen::Ref< const Eigen::MatrixXd > & noise_covariance_matrix)
Definition at line 190 of file GaussianMixture.cpp.
Referenced by bfl::UKFCorrection::correctStep(), and bfl::UKFPrediction::predictStep().
covariance() [1/6]
const Ref< const MatrixXd > GaussianMixture::covariance ()
Definition at line 130 of file GaussianMixture.cpp.
Referenced by bfl::KFCorrection::correctStep(), bfl::UKFCorrection::correctStep(), bfl::GPFCorrection::correctStep(), bfl::SUKFCorrection::correctStep(), bfl::KFPrediction::predictStep(), bfl::ResamplingWithPrior::resample(), bfl::Resampling::resample(), bfl::sigma_point::sigma_point(), and bfl::sigma_point::unscented_transform().
covariance() [2/6]
const Eigen::Ref<const Eigen::MatrixXd> bfl::GaussianMixture::covariance () const
covariance() [3/6]
Ref< MatrixXd > GaussianMixture::covariance (const std::size_t i)
Definition at line 136 of file GaussianMixture.cpp.
covariance() [4/6]
const Ref< const MatrixXd > GaussianMixture::covariance (const std::size_t i) const
Definition at line 154 of file GaussianMixture.cpp.
covariance() [5/6]
double & GaussianMixture::covariance (const std::size_t i, const std::size_t j, const std::size_t k)
Definition at line 142 of file GaussianMixture.cpp.
covariance() [6/6]
const double & GaussianMixture::covariance (const std::size_t i, const std::size_t j, const std::size_t k) const
Definition at line 160 of file GaussianMixture.cpp.
mean() [1/6]
const Ref< const MatrixXd > GaussianMixture::mean ()
Definition at line 94 of file GaussianMixture.cpp.
Referenced by bfl::KFCorrection::correctStep(), bfl::UKFCorrection::correctStep(), bfl::GPFCorrection::correctStep(), bfl::SUKFCorrection::correctStep(), bfl::KFPrediction::predictStep(), bfl::ResamplingWithPrior::resample(), bfl::Resampling::resample(), bfl::sigma_point::sigma_point(), and bfl::sigma_point::unscented_transform().
mean() [2/6]
const Eigen::Ref<const Eigen::MatrixXd> bfl::GaussianMixture::mean () const
mean() [3/6]
Ref< VectorXd > GaussianMixture::mean (const std::size_t i)
Definition at line 100 of file GaussianMixture.cpp.
mean() [4/6]
const Ref< const VectorXd > GaussianMixture::mean (const std::size_t i) const
Definition at line 118 of file GaussianMixture.cpp.
mean() [5/6]
double & GaussianMixture::mean (const std::size_t i, const std::size_t j)
Definition at line 106 of file GaussianMixture.cpp.
mean() [6/6]
const double & GaussianMixture::mean (const std::size_t i, const std::size_t j) const
Definition at line 124 of file GaussianMixture.cpp.
resize()
void GaussianMixture::resize (const std::size_t components, const std::size_t dim_linear, const std::size_t dim_circular = 0) [virtual]
Reimplemented in bfl::ParticleSet.
Definition at line 64 of file GaussianMixture.cpp.
Referenced by bfl::ParticleSet::resize(), and bfl::Gaussian::resize().
weight() [1/4]
const Ref< const VectorXd > GaussianMixture::weight ()
Definition at line 166 of file GaussianMixture.cpp.
Referenced by bfl::BootstrapCorrection::correctStep(), bfl::GPFCorrection::correctStep(), bfl::InitSurveillanceAreaGrid::initialize(), bfl::DrawParticles::predictStep(), bfl::GPFPrediction::predictStep(), bfl::ResamplingWithPrior::resample(), and bfl::Resampling::resample().
weight() [2/4]
const Eigen::Ref<const Eigen::VectorXd> bfl::GaussianMixture::weight () const
weight() [3/4]
double & GaussianMixture::weight (const std::size_t i)
Definition at line 172 of file GaussianMixture.cpp.
weight() [4/4]
const double & GaussianMixture::weight (const std::size_t i) const
Definition at line 184 of file GaussianMixture.cpp.
Member Data Documentation
components
std::size_t bfl::GaussianMixture::components
Definition at line 67 of file GaussianMixture.h.
Referenced by bfl::KFCorrection::correctStep(), bfl::UKFCorrection::correctStep(), bfl::GPFCorrection::correctStep(), bfl::SUKFCorrection::correctStep(), bfl::ParticleSet::operator+=(), bfl::KFPrediction::predictStep(), bfl::sigma_point::sigma_point(), and bfl::sigma_point::unscented_transform().
covariance_
Eigen::MatrixXd bfl::GaussianMixture::covariance_ [protected]
Definition at line 86 of file GaussianMixture.h.
Referenced by bfl::ParticleSet::operator+=().
dim
std::size_t bfl::GaussianMixture::dim
Definition at line 73 of file GaussianMixture.h.
Referenced by bfl::SUKFCorrection::correctStep(), and bfl::sigma_point::sigma_point().
dim_circular
std::size_t bfl::GaussianMixture::dim_circular
Definition at line 77 of file GaussianMixture.h.
Referenced by bfl::SUKFCorrection::correctStep(), bfl::ResamplingWithPrior::resample(), bfl::sigma_point::sigma_point(), and bfl::sigma_point::unscented_transform().
dim_circular_component
std::size_t bfl::GaussianMixture::dim_circular_component
Definition at line 71 of file GaussianMixture.h.
dim_covariance
std::size_t bfl::GaussianMixture::dim_covariance
Definition at line 81 of file GaussianMixture.h.
Referenced by bfl::sigma_point::sigma_point(), and bfl::sigma_point::unscented_transform().
dim_linear
std::size_t bfl::GaussianMixture::dim_linear
Definition at line 75 of file GaussianMixture.h.
Referenced by bfl::SUKFCorrection::correctStep(), bfl::ResamplingWithPrior::resample(), bfl::sigma_point::sigma_point(), and bfl::sigma_point::unscented_transform().
dim_noise
std::size_t bfl::GaussianMixture::dim_noise
Definition at line 79 of file GaussianMixture.h.
Referenced by bfl::sigma_point::sigma_point(), and bfl::sigma_point::unscented_transform().
mean_
Eigen::MatrixXd bfl::GaussianMixture::mean_ [protected]
Definition at line 84 of file GaussianMixture.h.
Referenced by bfl::ParticleSet::operator+=().
use_quaternion
bool bfl::GaussianMixture::use_quaternion
Definition at line 69 of file GaussianMixture.h.
Referenced by bfl::sigma_point::sigma_point(), and bfl::sigma_point::unscented_transform().
weight_
Eigen::VectorXd bfl::GaussianMixture::weight_ [protected]
Definition at line 88 of file GaussianMixture.h.
Referenced by bfl::ParticleSet::operator+=().
The documentation for this class was generated from the following files:
/home/user/bayes-filters-lib/src/BayesFilters/include/BayesFilters/GaussianMixture.h
/home/user/bayes-filters-lib/src/BayesFilters/src/GaussianMixture.cpp