bfl::VectorDescription Class Reference
#include <VectorDescription.h>
Public Types
enum CircularType { CircularType::Euler,
CircularType::Quaternion
 }
Public Member Functions
VectorDescription ()=default
VectorDescription (const std::size_t linear_components, const std::size_t circular_components=0, const std::size_t noise_components=0, const CircularType &circular_type=CircularType::Euler)
~VectorDescription ()=default
std::size_t linear_components () const
std::size_t circular_components () const
std::size_t noise_components () const
std::size_t linear_size () const
std::size_t circular_size () const
std::size_t noise_size () const
std::size_t total_size () const
std::size_t dof_size () const
void add_noise_components (const std::size_t &components)
VectorDescription noiseless_description () const
Public Attributes
CircularType circular_type = CircularType::Euler
Private Attributes
std::size_t linear_components_ = 0
std::size_t circular_components_ = 0
std::size_t noise_components_ = 0
Detailed Description
Definition at line 18 of file VectorDescription.h.
Member Enumeration Documentation
CircularType
enum bfl::VectorDescription::CircularType [strong]
Enumerator
Euler
Quaternion
Definition at line 21 of file VectorDescription.h.
Constructor & Destructor Documentation
VectorDescription() [1/2]
bfl::VectorDescription::VectorDescription () [default]
Referenced by noiseless_description().
VectorDescription() [2/2]
VectorDescription::VectorDescription (const std::size_t linear_components, const std::size_t circular_components = 0, const std::size_t noise_components = 0, const CircularType & circular_type = CircularType::Euler)
Definition at line 14 of file VectorDescription.cpp.
 VectorDescription()
bfl::VectorDescription::~VectorDescription () [default]
Member Function Documentation
add_noise_components()
void VectorDescription::add_noise_components (const std::size_t & components)
Definition at line 85 of file VectorDescription.cpp.
References noise_components_.
Referenced by bfl::AdditiveStateModel::getInputDescription().
circular_components()
std::size_t VectorDescription::circular_components () const
Definition at line 33 of file VectorDescription.cpp.
References circular_components_.
Referenced by dof_size(), and bfl::sigma_point::unscented_transform().
circular_size()
std::size_t VectorDescription::circular_size () const
Definition at line 51 of file VectorDescription.cpp.
References circular_components_, circular_type, and Quaternion.
Referenced by total_size().
dof_size()
std::size_t VectorDescription::dof_size () const
Definition at line 72 of file VectorDescription.cpp.
References circular_components(), circular_type, linear_size(), noise_size(), Quaternion, and total_size().
Referenced by bfl::sigma_point::UTWeight::UTWeight().
linear_components()
std::size_t VectorDescription::linear_components () const
Definition at line 27 of file VectorDescription.cpp.
References linear_components_.
Referenced by bfl::sigma_point::unscented_transform().
linear_size()
std::size_t VectorDescription::linear_size () const
Definition at line 45 of file VectorDescription.cpp.
References linear_components_.
Referenced by dof_size(), and total_size().
noise_components()
std::size_t VectorDescription::noise_components () const
Definition at line 39 of file VectorDescription.cpp.
References noise_components_.
noise_size()
std::size_t VectorDescription::noise_size () const
Definition at line 60 of file VectorDescription.cpp.
References noise_components_.
Referenced by dof_size(), and total_size().
noiseless_description()
VectorDescription VectorDescription::noiseless_description () const
Definition at line 91 of file VectorDescription.cpp.
References circular_components_, circular_type, linear_components_, and VectorDescription().
total_size()
std::size_t VectorDescription::total_size () const
Definition at line 66 of file VectorDescription.cpp.
References circular_size(), linear_size(), and noise_size().
Referenced by bfl::UKFCorrection::correctStep(), bfl::SUKFCorrection::correctStep(), dof_size(), and bfl::sigma_point::unscented_transform().
Member Data Documentation
circular_components_
std::size_t bfl::VectorDescription::circular_components_ = 0 [private]
Definition at line 55 of file VectorDescription.h.
Referenced by circular_components(), circular_size(), and noiseless_description().
circular_type
CircularType bfl::VectorDescription::circular_type = CircularType::Euler
Definition at line 49 of file VectorDescription.h.
Referenced by circular_size(), dof_size(), noiseless_description(), and bfl::sigma_point::unscented_transform().
linear_components_
std::size_t bfl::VectorDescription::linear_components_ = 0 [private]
Definition at line 53 of file VectorDescription.h.
Referenced by linear_components(), linear_size(), and noiseless_description().
noise_components_
std::size_t bfl::VectorDescription::noise_components_ = 0 [private]
Definition at line 57 of file VectorDescription.h.
Referenced by add_noise_components(), noise_components(), and noise_size().
The documentation for this class was generated from the following files:
/home/user/bayes-filters-lib/src/BayesFilters/include/BayesFilters/VectorDescription.h
/home/user/bayes-filters-lib/src/BayesFilters/src/VectorDescription.cpp