bfl::MeasurementModelDecorator Class Reference
#include <MeasurementModelDecorator.h>
Public Member Functions
std::pair< bool, bfl::Data > measure (const Data &data=Data()) const override
std::pair< bool, bfl::Data > predictedMeasure (const Eigen::Ref< const Eigen::MatrixXd > &cur_states) const override
std::pair< bool, bfl::Data > innovation (const bfl::Data &predicted_measurements, const bfl::Data &measurements) const override
std::pair< bool, Eigen::MatrixXd > getNoiseCovarianceMatrix () const override
bool setProperty (const std::string &property) override
bool freeze (const Data &data=Data()) override
std::pair< std::size_t, std::size_t > getOutputSize () const override
virtual VectorDescription getInputDescription () const
virtual VectorDescription getMeasurementDescription () const
bool enable_log (const std::string &folder_path, const std::string &file_name_prefix)
bool disable_log ()
std::string get_folder_path () const
std::string get_file_name_prefix () const
template<typename DatumType >
void logger (DatumType datum)
template<typename... DataType>
void logger (DataType... data)
template<typename DatumType >
void logger (DatumType datum) const
template<typename... DataType>
void logger (DataType... data) const
Protected Member Functions
MeasurementModelDecorator (std::unique_ptr< MeasurementModel > measurement_model) noexcept
MeasurementModelDecorator (MeasurementModelDecorator &&measurement_model) noexcept
virtual ~MeasurementModelDecorator () noexcept
MeasurementModelDecorator & operator= (MeasurementModelDecorator &&measurement_model) noexcept
virtual std::vector< std::string > log_file_names (const std::string &folder_path, const std::string &file_name_prefix)
virtual void log ()
Private Member Functions
template<typename DatumType >
void logger_helper (const size_t pos, DatumType datum)
template<typename DatumType , typename... DataType>
void logger_helper (const size_t pos, DatumType datum, DataType... data)
template<typename DatumType >
void logger_helper (const size_t pos, DatumType datum) const
template<typename DatumType , typename... DataType>
void logger_helper (const size_t pos, DatumType datum, DataType... data) const
Private Attributes
std::unique_ptr< MeasurementModel > measurement_model
std::string folder_path_
std::string file_name_prefix_
std::vector< std::string > file_names_
bool log_enabled_ = false
std::vector< std::ofstream > log_files_
Detailed Description
Definition at line 20 of file MeasurementModelDecorator.h.
Constructor & Destructor Documentation
MeasurementModelDecorator() [1/2]
MeasurementModelDecorator::MeasurementModelDecorator (std::unique_ptr< MeasurementModel > measurement_model) [protected], [noexcept]
Definition at line 14 of file MeasurementModelDecorator.cpp.
MeasurementModelDecorator() [2/2]
MeasurementModelDecorator::MeasurementModelDecorator (MeasurementModelDecorator && measurement_model) [protected], [noexcept]
Definition at line 18 of file MeasurementModelDecorator.cpp.
 MeasurementModelDecorator()
MeasurementModelDecorator::~MeasurementModelDecorator () [protected], [virtual], [noexcept]
Definition at line 22 of file MeasurementModelDecorator.cpp.
Member Function Documentation
disable_log()
bool Logger::disable_log () [inherited]
Definition at line 68 of file Logger.cpp.
References bfl::Logger::file_names_, bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
Referenced by bfl::Logger::~Logger().
enable_log()
bool Logger::enable_log (const std::string & folder_path, const std::string & file_name_prefix) [inherited]
Definition at line 22 of file Logger.cpp.
References bfl::Logger::file_name_prefix_, bfl::Logger::file_names_, bfl::Logger::folder_path_, bfl::Logger::log_enabled_, bfl::Logger::log_file_names(), and bfl::Logger::log_files_.
freeze()
bool MeasurementModelDecorator::freeze (const Data & data = Data()) [override], [virtual]
Implements bfl::MeasurementModel.
Definition at line 63 of file MeasurementModelDecorator.cpp.
get_file_name_prefix()
std::string Logger::get_file_name_prefix () const [inherited]
Definition at line 91 of file Logger.cpp.
References bfl::Logger::file_name_prefix_.
get_folder_path()
std::string Logger::get_folder_path () const [inherited]
Definition at line 85 of file Logger.cpp.
References bfl::Logger::folder_path_.
getInputDescription()
VectorDescription MeasurementModel::getInputDescription () const [virtual], [inherited]
Reimplemented in bfl::SimulatedLinearSensor.
Definition at line 30 of file MeasurementModel.cpp.
getMeasurementDescription()
VectorDescription MeasurementModel::getMeasurementDescription () const [virtual], [inherited]
Reimplemented in bfl::SimulatedLinearSensor.
Definition at line 37 of file MeasurementModel.cpp.
Referenced by bfl::UKFCorrection::correctStep(), and bfl::sigma_point::unscented_transform().
getNoiseCovarianceMatrix()
std::pair< bool, MatrixXd > MeasurementModelDecorator::getNoiseCovarianceMatrix () const [override], [virtual]
Reimplemented from bfl::MeasurementModel.
Definition at line 51 of file MeasurementModelDecorator.cpp.
getOutputSize()
std::pair< std::size_t, std::size_t > MeasurementModelDecorator::getOutputSize () const [override]
Definition at line 69 of file MeasurementModelDecorator.cpp.
innovation()
std::pair< bool, Data > MeasurementModelDecorator::innovation (const bfl::Data & predicted_measurements, const bfl::Data & measurements) const [override], [virtual]
Implements bfl::MeasurementModel.
Definition at line 45 of file MeasurementModelDecorator.cpp.
log()
void Logger::log () [protected], [virtual], [inherited]
Reimplemented in bfl::SimulatedStateModel, bfl::SIS, and bfl::SimulatedLinearSensor.
Definition at line 109 of file Logger.cpp.
log_file_names()
std::vector< std::string > Logger::log_file_names (const std::string & folder_path, const std::string & file_name_prefix) [protected], [virtual], [inherited]
Reimplemented in bfl::LinearModel, bfl::SimulatedStateModel, and bfl::SIS.
Definition at line 97 of file Logger.cpp.
Referenced by bfl::Logger::enable_log().
logger() [1/4]
template<typename... DataType>
void bfl::Logger::logger (DataType... data) [inline], [inherited]
Definition at line 42 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::logger_helper().
logger() [2/4]
template<typename... DataType>
void bfl::Logger::logger (DataType... data) const [inline], [inherited]
Definition at line 56 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::logger_helper().
logger() [3/4]
template<typename DatumType >
void bfl::Logger::logger (DatumType datum) [inline], [inherited]
Definition at line 35 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
Referenced by bfl::SimulatedLinearSensor::log().
logger() [4/4]
template<typename DatumType >
void bfl::Logger::logger (DatumType datum) const [inline], [inherited]
Definition at line 49 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
logger_helper() [1/4]
template<typename DatumType >
void bfl::Logger::logger_helper (const size_t pos, DatumType datum) [inline], [private], [inherited]
Definition at line 81 of file Logger.h.
References bfl::Logger::log_files_.
Referenced by bfl::Logger::logger(), and bfl::Logger::logger_helper().
logger_helper() [2/4]
template<typename DatumType >
void bfl::Logger::logger_helper (const size_t pos, DatumType datum) const [inline], [private], [inherited]
Definition at line 95 of file Logger.h.
References bfl::Logger::log_files_.
logger_helper() [3/4]
template<typename DatumType , typename... DataType>
void bfl::Logger::logger_helper (const size_t pos, DatumType datum, DataType... data) [inline], [private], [inherited]
Definition at line 87 of file Logger.h.
References bfl::Logger::log_files_, and bfl::Logger::logger_helper().
logger_helper() [4/4]
template<typename DatumType , typename... DataType>
void bfl::Logger::logger_helper (const size_t pos, DatumType datum, DataType... data) const [inline], [private], [inherited]
Definition at line 101 of file Logger.h.
References bfl::Logger::log_files_, and bfl::Logger::logger_helper().
measure()
std::pair< bool, Data > MeasurementModelDecorator::measure (const Data & data = Data()) const [override], [virtual]
Implements bfl::MeasurementModel.
Definition at line 33 of file MeasurementModelDecorator.cpp.
operator=()
MeasurementModelDecorator & MeasurementModelDecorator::operator= (MeasurementModelDecorator && measurement_model) [protected], [noexcept]
Definition at line 25 of file MeasurementModelDecorator.cpp.
predictedMeasure()
std::pair< bool, Data > MeasurementModelDecorator::predictedMeasure (const Eigen::Ref< const Eigen::MatrixXd > & cur_states) const [override], [virtual]
Implements bfl::MeasurementModel.
Definition at line 39 of file MeasurementModelDecorator.cpp.
setProperty()
bool MeasurementModelDecorator::setProperty (const std::string & property) [override], [virtual]
Reimplemented from bfl::MeasurementModel.
Definition at line 57 of file MeasurementModelDecorator.cpp.
Member Data Documentation
file_name_prefix_
std::string bfl::Logger::file_name_prefix_ [private], [inherited]
Definition at line 72 of file Logger.h.
Referenced by bfl::Logger::enable_log(), and bfl::Logger::get_file_name_prefix().
file_names_
std::vector<std::string> bfl::Logger::file_names_ [private], [inherited]
Definition at line 74 of file Logger.h.
Referenced by bfl::Logger::disable_log(), and bfl::Logger::enable_log().
folder_path_
std::string bfl::Logger::folder_path_ [private], [inherited]
Definition at line 70 of file Logger.h.
Referenced by bfl::Logger::enable_log(), and bfl::Logger::get_folder_path().
log_enabled_
bool bfl::Logger::log_enabled_ = false [private], [inherited]
Definition at line 76 of file Logger.h.
Referenced by bfl::Logger::disable_log(), bfl::Logger::enable_log(), bfl::Logger::logger(), and bfl::Logger::~Logger().
log_files_
std::vector<std::ofstream> bfl::Logger::log_files_ [mutable], [private], [inherited]
Definition at line 78 of file Logger.h.
Referenced by bfl::Logger::disable_log(), bfl::Logger::enable_log(), bfl::Logger::logger(), and bfl::Logger::logger_helper().
measurement_model
std::unique_ptr<MeasurementModel> bfl::MeasurementModelDecorator::measurement_model [private]
Definition at line 47 of file MeasurementModelDecorator.h.
The documentation for this class was generated from the following files:
/home/user/bayes-filters-lib/src/BayesFilters/include/BayesFilters/MeasurementModelDecorator.h
/home/user/bayes-filters-lib/src/BayesFilters/src/MeasurementModelDecorator.cpp