bfl::KFCorrection Class Reference
#include <KFCorrection.h>
Public Member Functions
KFCorrection (std::unique_ptr< LinearMeasurementModel > measurement_model) noexcept
KFCorrection (KFCorrection &&kf_prediction) noexcept
virtual ~KFCorrection () noexcept=default
MeasurementModel & getMeasurementModel () override
std::pair< bool, Eigen::VectorXd > getLikelihood () override
void correct (const GaussianMixture &pred_state, GaussianMixture &corr_state)
bool skip (const bool status)
bool freeze_measurements (const Data &data=Data())
Protected Member Functions
void correctStep (const GaussianMixture &pred_state, GaussianMixture &corr_state) override
Private Attributes
std::unique_ptr< LinearMeasurementModel > measurement_model_
Eigen::MatrixXd innovations_
GaussianMixture meas_covariances_
bool skip_ = false
Detailed Description
Definition at line 22 of file KFCorrection.h.
Constructor & Destructor Documentation
KFCorrection() [1/2]
KFCorrection::KFCorrection (std::unique_ptr< LinearMeasurementModel > measurement_model) [noexcept]
Definition at line 15 of file KFCorrection.cpp.
KFCorrection() [2/2]
KFCorrection::KFCorrection (KFCorrection && kf_prediction) [noexcept]
Definition at line 20 of file KFCorrection.cpp.
 KFCorrection()
virtual bfl::KFCorrection::~KFCorrection () [virtual], [default], [noexcept]
Member Function Documentation
correct()
void GaussianCorrection::correct (const GaussianMixture & pred_state, GaussianMixture & corr_state) [inherited]
Definition at line 16 of file GaussianCorrection.cpp.
correctStep()
void KFCorrection::correctStep (const GaussianMixture & pred_state, GaussianMixture & corr_state) [override], [protected], [virtual]
Implements bfl::GaussianCorrection.
Definition at line 46 of file KFCorrection.cpp.
References bfl::GaussianMixture::components, bfl::GaussianMixture::covariance(), and bfl::GaussianMixture::mean().
freeze_measurements()
bool GaussianCorrection::freeze_measurements (const Data & data = Data()) [inherited]
Definition at line 34 of file GaussianCorrection.cpp.
getLikelihood()
std::pair< bool, VectorXd > KFCorrection::getLikelihood () [override], [virtual]
Reimplemented from bfl::GaussianCorrection.
Definition at line 31 of file KFCorrection.cpp.
References bfl::utils::multivariate_gaussian_density().
getMeasurementModel()
MeasurementModel & KFCorrection::getMeasurementModel () [override], [virtual]
Implements bfl::GaussianCorrection.
Definition at line 25 of file KFCorrection.cpp.
skip()
bool GaussianCorrection::skip (const bool status) [inherited]
Definition at line 26 of file GaussianCorrection.cpp.
Member Data Documentation
innovations_
Eigen::MatrixXd bfl::KFCorrection::innovations_ [private]
Definition at line 42 of file KFCorrection.h.
meas_covariances_
GaussianMixture bfl::KFCorrection::meas_covariances_ [private]
Definition at line 44 of file KFCorrection.h.
measurement_model_
std::unique_ptr<LinearMeasurementModel> bfl::KFCorrection::measurement_model_ [private]
Definition at line 40 of file KFCorrection.h.
skip_
bool bfl::GaussianCorrection::skip_ = false [private], [inherited]
Definition at line 52 of file GaussianCorrection.h.
The documentation for this class was generated from the following files:
/home/user/bayes-filters-lib/src/BayesFilters/include/BayesFilters/KFCorrection.h
/home/user/bayes-filters-lib/src/BayesFilters/src/KFCorrection.cpp