bfl::sigma_point::UTWeight Struct Reference
#include <sigma_point.h>
Public Member Functions
UTWeight (std::size_t dof, const double alpha, const double beta, const double kappa)
Constructs the weights from number of degrees of freedom of the input space and UT parameters alpha, beta and kappa.
UTWeight (const VectorDescription &vector_description, const double alpha, const double beta, const double kappa)
Constructs the weights from a bfl::VectorDescription and UT parameters alpha, beta and kappa.
Public Attributes
Eigen::VectorXd mean
Eigen::VectorXd covariance
double c
c = sqrt(n + lambda) with lambda a ut parameter.
Detailed Description
Definition at line 37 of file sigma_point.h.
Constructor & Destructor Documentation
UTWeight() [1/2]
bfl::sigma_point::UTWeight::UTWeight (std::size_t dof, const double alpha, const double beta, const double kappa)
Constructs the weights from number of degrees of freedom of the input space and UT parameters alpha, beta and kappa.
Definition at line 22 of file sigma_point.cpp.
References bfl::sigma_point::unscented_weights().
UTWeight() [2/2]
bfl::sigma_point::UTWeight::UTWeight (const VectorDescription & vector_description, const double alpha, const double beta, const double kappa)
Constructs the weights from a bfl::VectorDescription and UT parameters alpha, beta and kappa.
The number of degress of freedom of the input space is determined from the vector description.
Definition at line 36 of file sigma_point.cpp.
References bfl::VectorDescription::dof_size(), and bfl::sigma_point::unscented_weights().
Member Data Documentation
c
double bfl::sigma_point::UTWeight::c
c = sqrt(n + lambda) with lambda a ut parameter.
Definition at line 46 of file sigma_point.h.
Referenced by bfl::sigma_point::unscented_transform().
covariance
Eigen::VectorXd bfl::sigma_point::UTWeight::covariance
Definition at line 41 of file sigma_point.h.
Referenced by bfl::sigma_point::unscented_transform().
mean
Eigen::VectorXd bfl::sigma_point::UTWeight::mean
Definition at line 39 of file sigma_point.h.
Referenced by bfl::sigma_point::unscented_transform().
The documentation for this struct was generated from the following files:
/home/user/bayes-filters-lib/src/BayesFilters/include/BayesFilters/sigma_point.h
/home/user/bayes-filters-lib/src/BayesFilters/src/sigma_point.cpp